language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
  - git clone https://github.com/google/textfsm
  - cd textfsm
  - python setup.py install
  - cd ..
  - curl -O https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
  - sudo dpkg -i influxdb_0.13.0_amd64.deb
  - sudo service influxdb start

script:
  - coverage run test_sshpoller.py

notifications:
  email: false

sudo: required

after_success:
  coveralls