language: python
python:
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
  - git clone https://github.com/google/textfsm
  - cd textfsm
  - python setup.py install
  - cd ..

script:
  - coverage run python test_sshpoller.py

notifications:
  email: false

sudo: false

after_success:
  coveralls